---
title: "Algal symbiont communities in urban vs offshore habitats in Miami"
authors: "Lorelei Ing, Michael Studivan"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 8
    fig_width: 8
    df_print: paged
    toc: yes
    toc_float: true
#bibliography: packages.bib
#nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# 1. Libraries and project set-up:

```{r libraries}
  library(tidyverse) # install.packages('tidyverse')
  # library(devtools)  # install.packages("devtools")
  # devtools::install_github("jrcunning/steponeR")
  # install.packages("rlang")         NOT NEEDED
  library(steponeR)
  # library(plyr)                     NOT NEEDED
  library(reshape2)
  # library(ggplot2)

```

#2. Calculate qPCR RATIOS fo all the samples  

```{r CalculateRatios, include=FALSE}

# Get the list of files with qPCR data
Plates <- list.files(path="data", pattern=".csv", full.names=T)
Plates # Plates 1-8 and 11-16 have Sample 12/NTC split across plates, so results .csv's were modified manually

# Run the steponeR program to get the S/H cell ratios
  # This needs to follow your plate target labels, otherwise it will not work

Urban_Out <- steponeR(files=Plates, target.ratios=c("B.A", "C.A", "D.A", "A.B", "C.B", "D.B", "A.C", "B.C", "D.C", "A.D", "B.D", "C.D"), 
                     fluor.norm=list(A=0, B=0, C=0, D=0),
                     copy.number=list(A=1, B=1, C=1, D=1), # look up copy numbers
                     ploidy=list(A=1, B=1, C=1, D=1),
                     extract=list(A=0.813, B=0.813, C= 0.813, D=0.813))

# Target ratio results
Urban<-Urban_Out$result
```

# 3. Data CLEANING A

```{r DataCleaning}
  # 1. Check and remove NTC wells                                   NOT NEEDED
    # ntc <- Urban[which(Urban$Sample.Name=="NTC"), ]
    # Urban <- droplevels(Urban[!rownames(Urban) %in% rownames(ntc), ])
    
  # 2. Check and remove + Control wells                             NOT NEEDED
    # Positive <- Urban[which(Urban$Sample.Name=="+"), ]
    # Urban <- droplevels(Urban[!rownames(Urban) %in% rownames(Positive), ])

  # 3.If Clade only detected in one technical replicate, set its ratio to NA and make them =0
    One_A<- Urban[which(Urban$A.reps==1),]
    # Urban$A.D[which(Urban$A.reps==1)] <- NA
    
    One_B<- Urban[which(Urban$B.reps==1),]
    # Urban$B.D[which(Urban$B.reps==1)] <- NA
    
    One_C<- Urban[which(Urban$C.reps==1),]
    # Urban$C.D[which(Urban$C.reps==1)] <- NA
    
    One_D<- Urban[which(Urban$D.reps==1),]
    # Urban$A.D[which(Urban$D.reps==1)] <- NA
    # Urban$B.D[which(Urban$D.reps==1)] <- NA
    # Urban$C.D[which(Urban$D.reps==1)] <- NA
   
    # Urban$A.D[is.na(Urban$A.D)] <- 0
    # Urban$B.D[is.na(Urban$B.D)] <- 0
    # Urban$C.D[is.na(Urban$C.D)] <- 0
    
```

# 4. Import the sample metadata

```{r Samples}
# 1. Get the sample information for your qPCR plates (if you use a template)        NOT NEEDED
  # SampleName<-read.csv("Metadata/Sample_Plates.csv") 
  # SampleName <- SampleName[!(is.na(SampleName$Sample.ID)), ]
  # SampleName<-SampleName[, -(10:34)]
  
# 2. Get the sample metadata
  Metadata<-read.csv("metadata.csv")
  Metadata$Species <- as.factor(Metadata$Species)
  Metadata$Region <- as.factor(Metadata$Region)
  Metadata$Site <- as.factor(Metadata$Site)
  Metadata$CollectionDate <- as.factor(Metadata$CollectionDate)
  Metadata$Season <- as.factor(Metadata$Season)
  Metadata$Rain <- as.factor(Metadata$Rain)

  #Sample.duplicates <-SampleName[duplicated(SampleName$Sample.Plate),]             NOT NEEDED
  
# 3. Create unique sample ID+FileName to relabel samples  
  Urban$Sample.Plate<-paste(Urban$Sample.Name, Urban$File.Name, sep = "_" )
  # head(SampleName)
  # head(Urban)
   
# Replace Sample.Names in qPCR data - Different for each project                    NOT NEEDED
# rownames(SampleName) <- SampleName$Sample.Plate
#     Urban$TP<-SampleName[as.character(Urban$Sample.Plate), "TP"]
#     Urban$Date<-SampleName[as.character(Urban$Sample.Plate), "Date"]
#     Urban$Date<-as.Date(Urban$Date, format="%m-%d-%y")
#     Urban$Fragment<-SampleName[as.character(Urban$Sample.Plate), "Fragment"]
#     Urban$Sample.ID<-SampleName[as.character(Urban$Sample.Plate), "Sample.ID"]
    
# Joining metadata with qPCR data
  Urban<-left_join(Urban, Metadata, by="Sample.Plate")

# Creates a unique ID for a core-sampling time                                      NOT NEEDED
  # Urban$Sample<-paste(Urban$Fragment, Urban$TP, sep='_') 
```

# 5. Dominant symbiont types and species/site filtering

```{r Species/Site means}
# Filtering by species, then determining Ct means for each symbiont by site
  Urban %>%
    filter(Species == "Mcav") -> Mcav

  Urban %>%
      filter(Species == "Ofav") -> Ofav
  
  Urban %>%
      filter(Species == "Cnat") -> Cnat

# The lowest mean Ct per site indicates the dominant symbiont genus
  Urban %>%
  filter(Species == "Mcav") %>%
  group_by(Site) %>%
  summarize(across(A.CT.mean:D.CT.mean, mean, na.rm=TRUE)) -> Mcav_dom

  Urban %>%
    filter(Species == "Ofav") %>%
    group_by(Site) %>%
    summarize(across(A.CT.mean:D.CT.mean, mean, na.rm=TRUE)) -> Ofav_dom
  
  Urban %>%
    filter(Species == "Cnat") %>%
    group_by(Site) %>%
    summarize(across(A.CT.mean:D.CT.mean, mean, na.rm=TRUE)) -> Cnat_dom
  
# Further filtering species by site based on dominant symbionts
  Mcav %>%
    filter(Region == "Miami offshore") -> Mcav_offshore
  Mcav %>%
      filter(Region == "Miami urban") -> Mcav_urban
  
  Ofav %>%
    filter(Region == "Miami offshore") -> Ofav_offshore
  Ofav %>%
      filter(Region == "Miami urban") -> Ofav_urban
  
  # Cnat %>% # Not needed since Cnat is dominated by D across all sites
  #   filter(Region == "Miami offshore") -> Cnat_offshore
  # Cnat %>%
  #     filter(Region == "Miami urban") -> Cnat_urban
```


#4. Get the total S/H cell ratios and log 10 transformations

```{r}
    # # Total SH                                                  NOT NEEDED
    # Urban$TotalSH<-(Urban$A.D + Urban$B.D+ Urban$C.D)
    # 
    # # Log 10
    #     Urban$logA.SH <- log10(Urban$A.D)
    #     Urban$logB.SH <- log10(Urban$B.D)
    #     Urban$logC.SH <- log10(Urban$C.D)
    #     Urban$logSH<-log10(Urban$TotalSH)
    #     
    #     Urban$logA.SH[which(Urban$A.D==0)] <- NA
    #     Urban$logB.SH[which(Urban$B.D==0)] <- NA
    #     Urban$logC.SH[which(Urban$C.D==0)] <- NA
  
```    


## 5. Data CLEANING B

```{r DataCleaningB}

# 5. Remove (-) control                                                   NOT NEEDED
    #NegControl <- Urban[which(Urban$Sample=="NA_NA"), ]
    #Urban <- droplevels(Urban[!rownames(Urban) %in% rownames(NegControl), ])

# 6.If coral detected in one technical replicate, remove the sample
    ReRun_Cnat <- Cnat[which(Cnat$D.reps==1), ] # no samples violate
    ReRun_Ofav_urban <- Ofav_urban[which(Ofav_urban$D.reps==1), ] # no samples violate
    ReRun_Ofav_offshore <- Ofav_offshore[which(Ofav_offshore$A.reps==1 | Ofav_offshore$B.reps==1), ] # 10 samples violate, but not all necessary to rerun
    ReRun_Mcav_offshore <- Mcav_offshore[which(Mcav_offshore$C.reps==1), ] # no samples violate
    ReRun_Mcav_urban <- Mcav_urban[which(Mcav_urban$D.reps==1 | Mcav_urban$A.reps==1), ] # 2 samples violate, but not necessary to rerun
    # Urban <- droplevels(Urban[!rownames(Urban) %in% rownames(ReRun.Coral), ])
    
    # NoHSratio <- Urban[which(Urban$TotalSH==0), ]                       NOT NEEDED
    # Urban <- droplevels(Urban[!rownames(Urban) %in% rownames(NoHSratio), ])
    
# 7. High ST    
    StDe1.5_Cnat <- Cnat[which(Cnat$D.CT.sd>1.5), ] # no samples violate
    StDe1.5_Ofav_urban <- Ofav_urban[which(Ofav_urban$D.CT.sd>1.5), ] # no samples violate
    StDe1.5_Ofav_offshore <- Ofav_offshore[which(Ofav_offshore$A.CT.sd>1.5 | Ofav_offshore$B.CT.sd>1.5), ] # 13 samples violate, but not all necessary to rerun
    StDe1.5_Mcav_offshore <- Mcav_offshore[which(Mcav_offshore$C.CT.sd>1.5), ] # no samples violate
    StDe1.5_Mcav_urban <- Mcav_urban[which(Mcav_urban$D.CT.sd>1.5 | Mcav_urban$A.CT.sd>1.5), ] # 13 samples violate, but not all necessary to rerun
    # Urban <- droplevels(Urban[!rownames(Urban) %in% rownames(StDe1.5), ])
  
# 8.Suspiciously late coral amplification                                 NOT NEEDED
    # Histo_Urban_CT<-qplot(Urban.CT.mean, data=Urban, binwidth=0.15)
    # Histo_Urban_CT 
  
  # LateCoral<-Urban[which(Urban$Urban.CT.mean>22), ]                     NOT NEEDED
  # Urban <- droplevels(Urban[!rownames(Urban) %in% rownames(LateCoral), ])
    
  # Samples to Re-run    
  # ToReRun_Cnat<-rbind(ReRun_Cnat, StDe1.5_Cnat)
  # ToReRun_Cnat<-ToReRun_Cnat %>% distinct()

```
  
#### 7. Chose bw samples ran more than once

```{r remove duplicates}

 ReRunA <- Urban[duplicated(Urban$Sample),] 
  n_RunA <- data.frame(table(Urban$Sample))
  colnames(n_RunA)<-c("Sample","RanA")
  Urban<-join(Urban, n_RunA, type = "left")
# 
  DuplicatesA <- Urban[(Urban$RanA>1),]
  # write.csv(DuplicatesA, "DuplicatesA.csv")

Duplicates<-ggplot(DuplicatesA, aes(Date, logSH, colour=factor(File.Name))) +
 stat_summary(fun=mean, geom="line") +   theme_gdocs() +
  geom_point() 
Duplicates
```

#### 8. Remove duplicates

```{r remove duplicates2}
    ToRem1<-read.csv("ToRemove.csv")
#     # 10/24/2018
   Urban<-Urban[!(Urban$Sample.Plate %in% ToRem1$Sample.Plate),]
# 
# # Check for replicates again--should have none
# 
  n_RunB <- data.frame(table(Urban$Sample))
  colnames(n_RunB)<-c("Sample","RanB")
  Urban<-join(Urban, n_RunB, type = "left")

# 
# # List of dupplicated samples, should have 0 rows now -->
   DuplicatesB <- Urban[(Urban$RanB>1),]
# # write.csv(DuplicatesB, file = 'DuplicatesB.csv')
```


```{r DProp, include=FALSE}

# Clade Proportion
  # D Proportion
  Urban$D.Prp<-(Urban$D.Urban/Urban$TotalSH)
  # C Proportion
  #Urban$C.Prp<-(Urban$C.SH/Urban$tot.SH)
  
  hist(Urban$D.Prp)
  Dproportion<-Urban[(Urban$D.Prp<1 & Urban$D.Prp>0.01),]
  hist(Dproportion$D.Prp)

```
  
## 9. Exploratory plots
  
```{r Proportions_dOMINANCE}

# A, B, VS D Community
  Urban$Community<-NULL
  Urban$Community[which(Urban$D.Prp<=0.5)] <- "AB"
  Urban$Community[which(Urban$D.Prp>0.5)] <- "D" 
  
  Dprop_Hist <- ggplot(Urban, aes (D.Prp, fill=as.factor(Temp))) +
 
      geom_histogram(binwidth = 0.01) + facet_wrap(~Nutrients) + 
      scale_x_continuous(name= expression(Proportion~of~italic(Symbiodinium)~D1),
                         breaks=c(0.98, 0.99, 1)) +
      scale_y_continuous(name= expression(Number~of~italic(O.faveolata)~fragments),
                         breaks=c(0, 10, 20, 30)) +
      theme(plot.background=element_blank(),
                         panel.grid.major.y = element_blank(),
                         panel.grid.major.x = element_blank(),
            legend.position=c(0.85,0.2),
                            legend.box.background = element_rect(), 
            panel.background =element_rect(fill = NA, color = "black")) +
  scale_fill_manual(values=c("blue", "red"),
                        name = "Temperature"# , 
                        #labels=c("C dominated", "D dominated")
                        )
  Dprop_Hist 
  
``` 

```{r}
# A, B, VS D Community
  
  SH_ratio <- ggplot(Urban, aes (as.factor(Temp), logSH, colour=(D.Prp))) +
      geom_point()+
      facet_wrap(Nutrients~Genotype)
  SH_ratio
  
  SH_ratio <- ggplot(Urban, aes (as.factor(Temp), logSH, colour=(Genotype))) +
      geom_point()+
      facet_wrap(~Nutrients)
  SH_ratio 
  
  D_proportion <- ggplot(Urban, aes (as.factor(Temp), D.Prp, colour=(Genotype))) +
      geom_point()+
      facet_wrap(~Nutrients)
  D_proportion 
  
```

```{r}
 # Urban$Community<-factor(as.character(Urban$Community), levels=c("C","CD", "DC", "D"))
  Urban$Community<-factor(as.character(Urban$Community), levels=c("AB", "D"))
  summary(Urban$Community)
  
  
  Urban.data<-Urban[,c("Genotype","Nutrients", "Temp", "Disease", "Treatment",
                     "A.D", "B.D", "D.Urban", "TotalSH", "logSH", "D.Prp", "Community",
                     "Sample", "Sample.ID", "TP", "Tank", "Date")]
 
  # Export data if want local backup
  # write.csv(Urban.data, file = 'Urban.csv')
  
  # End of qPCR data cleaning
```

